runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
env_variables:
  DATABASE_URL: "DATABASE_URL"
  GOOGLE_APPLICATION_CREDENTIALS: "GOOGLE_APPLICATION_CREDENTIALS"
